version: '2'

services:
  nginx:
    container_name: node-nginx-lb
    build: ./nginx
    links:
      - app:app
    ports:
      - 3000:80
    depends_on:
      - app

  app:
    container_name: node_nginx
    image: node-nginx:test
    ports:
      - 3000
